package org.apache.struts.apps.blank;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

//Generated by Selenium IDE
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import io.github.bonigarcia.wdm.WebDriverManager;

public class BlankVerifyWelcomeIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  private JavascriptExecutor js;
  private String home;

  @BeforeEach
  public void setUp() {
    driver = WebDriverManager.getInstance().create();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    home = "http://localhost:"
            + System.getProperty("cargo.servlet.port")
            + "/struts-blank/";
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void blankVerifyWelcome() {
    // Test name: blank-verify-welcome
    // Step # | name | target | value
    // 1 | open | struts-blank/Welcome.do |
    driver.get(home + "Welcome.do");
    // 2 | verifyTitle | Struts Blank Application |
    assertEquals("Struts Blank Application", driver.getTitle());
    // 3 | executeScript | location.reload(); return document.title; | title
    vars.put("title", js.executeScript("location.reload(); return document.title;"));
    // 4 | verify | title | Struts Blank Application
    assertEquals("Struts Blank Application", vars.get("title").toString());
    // 5 | assertElementPresent | xpath=//*[contains(text(),'Welcome!')] |
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[contains(text(),\'Welcome!\')]"));
      assertTrue(elements.size() > 0);
    }
  }
}