package org.apache.struts.apps;

//Generated by Selenium IDE
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

import io.github.bonigarcia.wdm.WebDriverManager;

public class BlankVerifyWelcomeIT {
  private WebDriver driver;
  private String port;

  @BeforeEach
  public void setUp() {
    driver = WebDriverManager.getInstance().create();
    port = System.getProperty("cargo.servlet.port");
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void blankverifywelcome() {
    // Test name: blank-verify-welcome
    // Step # | name | target | value | comment
    // 1 | open | struts-blank/Welcome.do |  | 
    driver.get("http://localhost:" + port + "/struts-blank/Welcome.do");
    // 2 | verifyTitle | Struts Blank Application |  | 
    assertEquals("Struts Blank Application", driver.getTitle());
    // 3 | assertElementPresent | xpath=//*[contains(text(),'Welcome!')] |  | 
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[contains(text(),\'Welcome!\')]"));
      assertTrue(elements.size() > 0);
    }
  }

  /**
   * For JDK 1.7 compatibility
   * <em>Assert</em> that {@code expected} and {@code actual} are equal.
   * <p>If both are {@code null}, they are considered equal.
   *
   * @see Object#equals(Object)
   */
  public static void assertEquals(Object expected, Object actual) {
    Assertions.assertEquals(expected, actual);
  }

  /**
   * For JDK 1.7 compatibility
   * <em>Assert</em> that the supplied {@code condition} is {@code true}.
   */
  public static void assertTrue(boolean condition) {
    Assertions.assertTrue(condition);
  }
}
